// Author: Dylan Muller
// Student Number: MLLDYL002

#ifndef _USB_H
#define _USB_H


// USB driver (V-USB) definitions

#define USB_CFG_CHECK_CRC       0
#define USB_CFG_VENDOR_NAME 'U', 'S', 'B', '-', '2', '3', '2'
#define USB_CFG_HAVE_INTRIN_ENDPOINT3 1
#define USB_CFG_IOPORTNAME      D
#define USB_CFG_IMPLEMENT_HALT 0
#define USB_CFG_MAX_BUS_POWER 100
#define USB_CFG_IMPLEMENT_FN_WRITE 1
#define USB_COUNT_SOF 0
#define USB_CFG_DESCR_PROPS_STRING_VENDOR 0
#define USB_CFG_DEVICE_ID 0xe1, 0x05 
#define USB_CFG_CLOCK_KHZ (F_CPU/1000)
#define USB_CFG_DESCR_PROPS_STRINGS 0
#define USB_CFG_CHECK_DATA_TOGGLING 0
#define USB_CFG_INTERFACE_SUBCLASS 2       
#define USB_CFG_INTERFACE_PROTOCOL 1   
#define USB_CFG_DESCR_PROPS_DEVICE 0
#define USB_CFG_DESCR_PROPS_CONFIGURATION USB_PROP_IS_DYNAMIC
#define USB_CFG_HAVE_MEASURE_FRAME_LENGTH 0
#define USB_USE_FAST_CRC 0
#define USB_CFG_EP3_NUMBER  3
#define USB_CFG_VENDOR_ID 0xc0, 0x16 
#define USB_CFG_DMINUS_BIT 3
#define USB_CFG_DEVICE_VERSION  0x00, 0x01
#define USB_CFG_VENDOR_NAME_LEN 7
#define USB_CFG_IMPLEMENT_FN_WRITEOUT 1
#define USB_CFG_HAVE_FLOWCONTROL 1
#define USB_CFG_DRIVER_FLASH_PAGE 0
#define USB_CFG_LONG_TRANSFERS 0
#define USB_CFG_HAVE_INTRIN_ENDPOINT  1
#define USB_CFG_DESCR_PROPS_STRING_PRODUCT 0
#define USB_CFG_DEVICE_NAME_LEN 7
#define USB_CFG_DEVICE_CLASS  2    
#define USB_CFG_DEVICE_SUBCLASS 0
#define USB_CFG_INTERFACE_CLASS 2       
#define USB_CFG_DPLUS_BIT       2
#define USB_CFG_DESCR_PROPS_STRING_0 0
#define USB_CFG_IMPLEMENT_FN_READ 1
#define USB_CFG_SUPPRESS_INTR_CODE 0
#define USB_CFG_INTR_POLL_INTERVAL 255
#define USB_CFG_IS_SELF_POWERED 0
#define USB_CFG_DEVICE_NAME 'U', 'S', 'B', '-', '2', '3', '2'
#define USB_CFG_DESCR_PROPS_STRING_SERIAL_NUMBER 0
#define USB_CFG_DESCR_PROPS_HID 0
#define USB_CFG_DESCR_PROPS_HID_REPORT 0
#define USB_CFG_DESCR_PROPS_UNKNOWN  0

#ifndef SIG_INTERRUPT0
#define SIG_INTERRUPT0			_VECTOR(1)
#endif

#endif 
